/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SuicideAwarenessWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;

import Business.Organization.SuicideAwarenessOrganization;
import Business.User.UserAccount;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chaitanya
 */
public class SuicideAwarenessWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuicideAwarenessWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private SuicideAwarenessOrganization suiAwaOrg;
    private Enterprise etrp;
    private EcoSystem business;
    

    

    public SuicideAwarenessWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SuicideAwarenessOrganization suicideAwarenessOrganization, Enterprise etrp, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.suiAwaOrg=suicideAwarenessOrganization;
        this.etrp=etrp;
        this.business=business;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageWorkRequests = new javax.swing.JButton();

        btnManageWorkRequests.setText("Manage Work Requests");
        btnManageWorkRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWorkRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnManageWorkRequests)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnManageWorkRequests)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageWorkRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWorkRequestsActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add(new ManageSAOfficerRequestJPanel(userProcessContainer, account, suiAwaOrg, etrp, business));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnManageWorkRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageWorkRequests;
    // End of variables declaration//GEN-END:variables
}
